### ISSUE TITLE
Issue with ACL evaluation

### ISSUE THREAD

**Issue by ela34** [nyambati/express-acl#108]
I think (at least from my point a view) there is a logic issue in the way ACLs are evaluated. Given the ACL below, if I connect to "api/version" using GET, I get an error.
From my understanding the ACL below should not reject this action.

```
	{
		"group": "guest",
		"permissions": [
			{
				"resource": "*",
				"methods": ["OPTIONS"],
				"action": "allow"
			},
			{
				"resource": "/api/version/*",
				"methods": "*",
				"action": "allow"
			},
              ]
       }
```

This can be fixed by changing the code in 'common.js' around line 184 to something like:

```
    if (matchUrlToResource(route, resource)) {
      if (isAllowed(method, permission))
      	return permission;
    }
 
```

In fact resource evaluation should continue until there is no more chance an 'allow' is found, this is consistent with the fact that'deny' is the default action.
What do you think?

**Comment by shubhpaliwal** [comment]
I think there is problem in it's lib folder "common.js" file.
node-modules/express-acl/lib/common.js file..

I was having the issue that i had an authenticated user but was not able to access one of the resouce, even after defining that in its json file and js file..

I think there is problem in function findRoleFromRequest function's objectPath.get() this is not working..
so u can define your custom condition and that should work..
It worked for me..

**Comment by nyambati** [comment]
@ela34 Would you mind making a PR on this.
