### ISSUE TITLE
Always return status code 200

### ISSUE THREAD

**Issue by WindyDay** [nyambati/express-acl#109]
In lib/common.js
`const checkIfHasAccess = (
  method,
  res,
  next,
  permission,
  customMessage,
  response
) => {
  if (isAllowed(method, permission)) {
    return next();
  }
  return res.json(deny(customMessage, response));
};`

I alway get status 200 because of this line
`return res.json(deny(customMessage, response));`
it should be replaced by this
`return res.status(403).json(deny(customMessage, response));`

**Comment by abdulrahman-khankan** [comment]
@nyambati it still returns 200, I am using 2.0.3 which has the fix mentioned above.
