### ISSUE TITLE
ES6 import syntax

### ISSUE THREAD

**Issue by dagovalsusa** [nyambati/express-acl#126]
in a TS project

`import acl from 'express-acl';`

and also

`import * as acl from 'express-acl';`

return error "declaration file not found"

**Comment by nyambati** [comment]
@dagovalsusa This is because this module does not include Typescript declarations types

**Comment by dagovalsusa** [comment]
So, can I not use the ES6 syntax?
Are you planning to insert it, or can you tell me how I can do it?
Thanks

**Comment by nyambati** [comment]
You can add a file called `express-acl.d.ts` on your project and add this code `declare module 'express-acl'`. This should fix your issue.
