### ISSUE TITLE
Dynamic roles based on database.

### ISSUE THREAD

**Issue by mits87** [nyambati/express-acl#150]
Hello, 
a quick question. I have all ACLs in my DB and based on logged in user I have different roles (based on many conditions).
Is it possible to pass dynamically a `rules` object or even better use some attribute like: rulesObjectName etc. to pass from where rules should be applied ? 

Thank you in advance for your answer

**Comment by Monir-Shembesh** [comment]
Hi @mits87 , I am wondering if this is possible too? What database are you using as well as if I can pass the rules dynamically when the user tries to make a http request to one of my endpoints? 

Thank you
