### ISSUE TITLE
Provide way to persist rules in database.

### ISSUE THREAD

**Issue by nyambati** [nyambati/express-acl#54]
# Objective

This feature will enable storing of ACL configuration rules in a database for persistence. This will make the configuration rules portable and easy to manage if used in multiple apps.

**Comment by cjndubisi** [comment]
I'll like to help out with this issue, but I'll need you to shed more light on this especially;

"This will make the configuration rules portable and easy to manage if used in multiple apps".

 A simple use case will be good.

**Comment by goizueta** [comment]
@akabiru maybe you could provide more context on this for @cjndubisi?

**Comment by akabiru** [comment]
@goizueta @andela-thomas might be in a better position to flesh it out.

**Comment by cjndubisi** [comment]
Action Plan:

- Read up on redis (use online tutorials) - 1/2 day
- Read source code to find the best way to integrate redis into express-acl - 1/2 day
- Integrate redis into express-acl - 1 day
    - use .env port and host for app & redis 
    - fetch config from redis else read from file
- write tests cases - 1 day

Start date: Thursday, 25th Nov. 
Expected end date: Monday, 27th Mov.

**Comment by andela-thomas** [comment]
@cjndubisi Make sure you install ZenHub so that we can track your progress

**Comment by cjndubisi** [comment]
Hi @andela-thomas, I have completed Redis integration, however 24/71 tests are failing. Last we talked, the asynchronous nature of Redis in the `acl.config` seems to be the problem. 

I'll try adding this feature as a plugin `var acl_redis = require('express-acl/redis')`.

**Comment by adesege** [comment]
Has this issue been solved?

**Comment by nyambati** [comment]
@adesege Not really, I am currently making some few rewrite to support sub routing, once that is done we can revisit this issue
