### ISSUE TITLE
Restrict access to certain subroutes under main route

### ISSUE THREAD

**Issue by techgyani** [nyambati/express-acl#66]
Assume : Following are the 2 routes in express APP:

1. GET /user/:user_id
2. GET /user/:user_id/approve

I want to give access to route no 1 to system admin but route no 2 to super admin only. How can I achieve that with this library?

I have version 1.0.0 installed on my system, I reviewed the code of Module. I think, if I will allow GET USER permission to any user, user will be able to access all child routes under user endpoint.

**Comment by nyambati** [comment]
@techgyani The functionality you are referring to is not possible at the moment but it is something worth looking into. Do you have any suggestion on how we could go about this?

**Comment by bhupendra-mp** [comment]
I dug deeper in express code and I think this is not possible until you write a route middleware. Value of route path comes in route middleware under req.route.path.

**Comment by nyambati** [comment]
@bhupendra-mp Do you have any suggestion on a way we can approach this problem? I am looking into it but ideas are welcome.

**Comment by nyambati** [comment]
@techgyani This functionality has been fulfilled on this PR #91
