### ISSUE TITLE
Request to add anonymous role for default acl case

### ISSUE THREAD

**Issue by nitish24p** [nyambati/express-acl#70]
Currently when a role is not found, the acl layer throws a 404 because its unable to find the suitable role. How does one handle a default role in case a user has a default role as anonymous

**Comment by nyambati** [comment]
@nitish24p This is a functionality we don't have at the moment, Would you like take a short at it?

**Comment by nyambati** [comment]
@nitish24p This Issue has been resolved with PR #72, Thanks for your contribution. Will be updating the changes to a new release.
