### ISSUE TITLE
Default config file path is module path

### ISSUE THREAD

**Issue by franz-josef-kaiser** [nyambati/express-acl#76]
The config file per default is searched [_inside the module dir_](https://github.com/nyambati/express-acl/blob/9661e939262cce4fb2591bf2b3b8fef349a532a8/lib/nacl.js#L20-L49), which will fail miserably. This also forces implementations to use absolute paths. 

### Failing example:

```
/* roles.js */
import acl from 'express-acl'

acl.config({
    yml: true,
    filename: 'roles.yml',
})
```

### Working example:

```
/* roles.js */
import acl from 'express-acl'

acl.config({
    yml: true,
    path: __dirname,
    filename: 'roles.yml',
})
```

_IMHO_ the default should be the `pwd` or other _project_ related root path.

**Comment by nyambati** [comment]
@franz-josef-kaiser Thanks for raising the issue. Would you mind making a PR on the same? Would appreciate your contribution.

**Comment by franz-josef-kaiser** [comment]
@nyambati Do you have an idea (as in code sample, fn you would like to use) for a PR?

**Comment by nyambati** [comment]
@franz-josef-kaiser Let me look  into all the scenarios an will get back to you
