### ISSUE TITLE
Deny is not invoked when role is not provided as a string

### ISSUE THREAD

**Issue by HussainAliAkbar** [nyambati/express-acl#79]
Hi,
I found this bug in express-acl. I'm going to describe it below. Can you please let me know if this is a valid bug or not? i have fixed it as well and can make a PR for it as well if you want.

**The issue:**

Currently what happens is that if i set a role to any value with type integer or any other type (which is not a string) , express acl validates it in the authorize function with the following code:

`if (!_.isString(role) || !role) return;`

the !role condition will never be true because express-acl by default sets a role to guest if no role is provided at all. However the !_.isString(will be false) if the role is not provided as a string. But instead of calling the deny function, this simply returns ( not next() ) which is causing my application to get stuck. I think that this issue would persist for everyone because neither next is being called nor is the deny function. 

I believe that in this case the deny function should be called with the error that the role is not provided as a string.

Like i said, i have already fixed this on my end. Happy to make a PR for it if you approve.

Thanks!

**Comment by nyambati** [comment]
@HussainAliAkbar Thanks for picking this up. Your contribution is welcome.
