### ISSUE TITLE
Can you clarify the need for baseUrl

### ISSUE THREAD

**Issue by viktorivanov** [nyambati/express-acl#82]
Hi,
I have read the documentation and would like a clarification on something:
If I want to make acl work for all my 'api'-prefixed routes I would need to add
```javascript
acl.config({
    baseUrl: 'api',
   // other configurations...
})
```
and every request will be allowed or denied based on my configuration file (nacl.yml/nacl.json), right?

But in my current situation routes that are not starting with 'api' have response (for example /auth/register)
```json
{
  "status": "Access denied",
  "success": false,
  "message": "REQUIRED: Policy not found"
}
```
I thought that only routes matching the baseUrl will be checked by the plugin...

**Comment by nyambati** [comment]
@viktorivanov Sorry for the late reply, the base url is used to locate the resource from the url. Assuming we have a path that looks like this `/api/v1/users`.
Our resource here will be users and base URL `/api/v1`. By specifying this we can accurately pick the resource from this path and find the coresponding policy in the specified rules. This is done ny this method
```js
function resource(next, url, baseUrl) {
  let base = (baseUrl) ? baseUrl.match(/([A-Z])\w+/gi) : '';
  let lengthOfTheBaseUrl = (base) ? base.length : 0;
  let arr = url.match(/([A-Z])\w+/gi);

  if (arr) return arr.splice(lengthOfTheBaseUrl)[0];

  return next();
}```

Without the base url this module will assume your `api` to be your resource. The above method does not really cater for some use cases I am actively looking for ways to make it better. If you have any ideas on this they are welcome.
