### ISSUE TITLE
Resource name with hyphen (dash) throws "REQUIRED: Policy not found"

### ISSUE THREAD

**Issue by kunal-dethe-v2sol** [nyambati/express-acl#88]
When url is set as `../user-roles` or `../functional-areas` i.e. with a hyphen (dash) 

and permission set as;

    {
        "resource": "job-roles",
        "methods": [
            "GET"
        ],
        "action": "allow"
    },
    {
        "resource": "functional-areas",
        "methods": [
            "GET"
        ],
        "action": "allow"
    }

the request returns with following error:

    {"status":"Access denied","success":false,"message":"REQUIRED: Policy not found"}

If the same is changed to: `../user_roles` or `../functional_areas` it works properly.

Any idea why?

**Comment by nyambati** [comment]
@kunal-dethe-v2sol Let me look into it

**Comment by nyambati** [comment]
@kunal-dethe-v2sol I am currently revising the codebase with a different approach. The will be available for review and this is one the bugs I am targeting to fix.
