### ISSUE TITLE
Cannot set other configuration options if rules field is set. 

### ISSUE THREAD

**Issue by dominicrathbone** [nyambati/express-acl#96]
https://github.com/nyambati/express-acl/blob/73f4c96c0cd3cc326c8c0c90882645d3d840acb3/lib/index.js#L20,L25

I am trying to use the rules properties to set my rules instead of a json/yaml file but it seems to short circuits the config function before it sets the rest of my configuration properties. Is there a different way to deal with this use case?

**Comment by dominicrathbone** [comment]
I have got around this for now by calling the config function twice:

Once with the configuration properties, excluding rules, wrapped in a try/empty catch (to deal with the filePath error) and a second time with the rules.

`try {
  acl.config(aclConfiguration, aclResponse);
} catch (err) {
  // Do nothing, fix to get around shortcircuitting issue described here:
}

acl.config({ rules: [publicRule, userRule, adminRule] }, aclResponse);`

**Comment by nyambati** [comment]
@dominicrathbone Thanks for raising this, I will look into this and keep you updated on the progress.

**Comment by dominicrathbone** [comment]
Thanks, great job otherwise!

**Comment by nyambati** [comment]
@dominicrathbone Just made the changes can you review the PR and let me know if this fixes your issue. You review will be appreciated.
