### ISSUE TITLE
Access is denied if query parameter is present.

### ISSUE THREAD

**Issue by dominicrathbone** [nyambati/express-acl#98]
https://github.com/nyambati/express-acl/blob/73f4c96c0cd3cc326c8c0c90882645d3d840acb3/lib/index.js#L70

originalUrl being passed through as route for findPermissionForRoute function includes the query parameters. Unless you explicitly have a policy to match against the query parameter and it's value exactly, access will be denied as no permissions will be found for the path.

**Comment by nyambati** [comment]
@dominicrathbone Your issue has been fixed with PR #101. Feel free to review and close this issue once you are content with the changes.
