### ISSUE TITLE
decodedObjectName and searchPath does not allow to map custom role property

### ISSUE THREAD

**Issue by aman2talk** [nyambati/express-acl#99]
Hi 
I am using the role propery in my session as **req.session.user.role**. But As the doc says by default it search the role either req.decoded or req.session. To mach the custom location we can use decodedObjectName searchPath. 

I have tried different combinations but still no luck. If explicitly I make the role accessible via **req.session.role**. It works. But I want to change it to req.session.user.role.

How to achieve this?

Thanks.

**Comment by aman2talk** [comment]
Hi,

I just reviewed the module code and realised that Readme.md file is not up to date. The correct property name is **roleSearchPath** instead of **searchPath**. If anyone needs to change the path to check for user's role in request object then you can use the it as follows:

````js
acl.config({
    roleSearchPath : 'session.user.role' // whatever value you will pass here will be prefixed with req.
});
````

**Comment by nyambati** [comment]
@aman2talk Thanks for raising this I will update the documentation to avoid further confusion.

**Comment by nyambati** [comment]
@aman2talk I have just made the update on PR #100. Thank you for your input.

**Comment by aman2talk** [comment]
@nyambati Thanks for the update. Closing the issue.
